# Densities of used materials
Densities:
  # Mapping densities names to kg/m3
  # 'steel', 'insulation', 'water' are mandatory
  # OBM calculated using EXPERT layer in average thickness
  # OBM calculate: [(]thickness*100 kg/m3 + 2 kg/m2 (EXPERT layer)]/thickness
  zero: 0
  steel: 7850
  insulation: 150
  water: 1000
  polypropylene: 1000
  copper: 2000
  wool: 30
  OBM5F: 500
  OBM13F: 250
  OBM40F: 150



# Ducts. Default values of thickness of duct according to Appendix K of SP 60.13330.2020
Thickness by diameter:
  # Mapping ducts diameters to thicknesses
  # Key - maximum diameter
  # Value - thickness in mm
  # Thickness for all diameters higher than maximum will be calculated as for the maximum presented diameter
  200: 0.5
  450: 0.7
  800: 0.9
  1250: 1.0
  1600: 1.2
  2000: 1.4

Thickness by width:
  # Mapping ducts width to thicknesses
  # Key - maximum width
  # Value - thickness in mm
  # Thickness for all width higher than maximum will be calculated as for the maximum presented width
  250: 0.5
  1000: 0.7
  2000: 0.9

Insulation types:
  None: zero
  1: wool
  2: wool
  3: wool
  4: wool
  5: OBM5F
  6: OBM13F
  7: OBM40F


# Pipes
Pipes densities:
  # Mapping pipes types to Density list.
  # Key - any text in Type name.
  # Value - key from Density list
  # All unknown types will be expected steel
  Steal: steel
  Steel: steel
  Электросвар: steel
  Iron: steel
  Cooper: copper
  Copper: copper
  PP-R: polypropylene
  ПЭ: polypropylene
  PE: polypropylene
  ABN: polypropylene
  Poly: polypropylene
  PVC: polypropylene

Pipes filling ratios:
  # Mapping pipes types to filling ratios (how much filling is expected in a pipe).
  # Key - any text in Type name.
  # Value - ratio
  # All unknown types will be expected as 1.0 (fully filled)
  Drenage: 0.5
  RC_CastIron_PAM: 0.5
  RC_PVC_Gravity_Chemkor_SN8: 0.5
  Sanitary_Socket: 0.5


# Cable Trays
Cable trays filling ratio: 0.65
Cables average density: 3360